SELECT DATE_FORMAT(U.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, U.PRODUCT_ID, U.USER_ID, U.SALES_AMOUNT
FROM (
    SELECT A.SALES_DATE, A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
    FROM ONLINE_SALE as A
    UNION ALL
    SELECT B.SALES_DATE, B.PRODUCT_ID, NULL AS USER_ID, B.SALES_AMOUNT
    FROM OFFLINE_SALE as B) as U
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY U.SALES_DATE, U.PRODUCT_ID, U.USER_ID