SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO AS I
JOIN ONLINE_SALE AS O
ON I.USER_ID = O.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3