SELECT SUM(G.SCORE) as SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES as E JOIN HR_GRADE as G
ON E.EMP_NO = G.EMP_NO
GROUP BY G.YEAR, G.EMP_NO
HAVING G.YEAR = '2022'
ORDER BY 1 DESC
LIMIT 1;